/*
 *
 * 대상 설치본 버전: InfraEye-2.0.0.241127-STD.tar.gz,  infra2_img_2.0.0_250204.tar.gz
 * 패치본 생성일: 2025-10-27
 * 주요 내용: SMS 추가
 *
 * DDL (롤백불가. 쿼리 중 오류 발생 시 DROP TABLE.. 문 수동 수행)
 *
 * DROP TABLE IF EXISTS NMS_DB.SMS_SERVICE_MONITOR_POLICY_DETAIL;
 * DROP TABLE IF EXISTS NMS_DB.SMS_SERVICE_MONITOR_POLICY_DETAIL;
 * DROP TABLE IF EXISTS NMS_DB.SMS_SERVICE_MONITOR_POLICY;
 * DROP TABLE IF EXISTS NMS_DB.SMS_LOG_MONITOR_POLICY_DETAIL;
 * DROP TABLE IF EXISTS NMS_DB.SMS_LOG_MONITOR_POLICY;
 * DROP TABLE IF EXISTS NMS_DB.SMS_FILE_MONITOR_POLICY_DETAIL;
 * DROP TABLE IF EXISTS NMS_DB.SMS_FILE_MONITOR_POLICY;
 * DROP TABLE IF EXISTS NMS_DB.SMS_EX_TIME_AGENT_MAPPING;
 * DROP TABLE IF EXISTS NMS_DB.SMS_EX_TIME_INDICATOR_MAPPING;
 * DROP TABLE IF EXISTS NMS_DB.SMS_EX_TIME_SCHEDULE_HOLIDAY;
 * DROP TABLE IF EXISTS NMS_DB.SMS_EX_TIME_SCHEDULE_MONTHLY;
 * DROP TABLE IF EXISTS NMS_DB.SMS_EX_TIME_SCHEDULE_WEEKLY;
 * DROP TABLE IF EXISTS NMS_DB.SMS_EX_TIME_SCHEDULE;
 * DROP TABLE IF EXISTS NMS_DB.SMS_EX_TIME_TMPL;
 * DROP TABLE IF EXISTS NMS_DB.SMS_PROCESS_COMMAND_HISTORY;
 * DROP TABLE IF EXISTS NMS_DB.SMS_PROCESS_THRESHOLD;
 * DROP TABLE IF EXISTS NMS_DB.SMS_PROCESS_COMMAND;
 * DROP TABLE IF EXISTS NMS_DB.SMS_PROCESS_MAPPING;
 * DROP TABLE IF EXISTS NMS_DB.SMS_PROCESS;
 * DROP TABLE IF EXISTS NMS_DB.SMS_EVENT_POLICY_TMPL_MAPPING;
 * DROP TABLE IF EXISTS NMS_DB.SMS_EVENT_POLICY_THRESHOLD_CONDITION;
 * DROP TABLE IF EXISTS NMS_DB.SMS_EVENT_POLICY_THRESHOLD;
 * DROP TABLE IF EXISTS NMS_DB.SMS_EVENT_POLICY_MAPPING;
 * DROP TABLE IF EXISTS NMS_DB.SMS_EVENT_POLICY_TMPL;
 * DROP TABLE IF EXISTS NMS_DB.SMS_AGENT_JOB_HISTORY;
 * DROP TABLE IF EXISTS NMS_DB.SMS_AGENT_HISTORY;
 * DROP TABLE IF EXISTS NMS_DB.SMS_AGENT_POLICY_MAPPING;
 * DROP TABLE IF EXISTS NMS_DB.SMS_AGENT_POLICY_TMPL_INDICATOR;
 * DROP TABLE IF EXISTS NMS_DB.SMS_AGENT_POLICY_TMPL;
 * DROP TABLE IF EXISTS NMS_DB.SMS_INDICATOR;
 * DROP TABLE IF EXISTS NMS_DB.SMS_AGENT;
 * DROP TABLE IF EXISTS NMS_DB.SMS_AGENT_FILE;
 * ALTER TABLE NMS_DB.SMS_INFO DROP COLUMN `SERIAL_NO`;
 * */

USE NMS_DB;

-- 릴리즈 버전 관리 테이블
CREATE TABLE IF NOT EXISTS CM_DB.VERSION_HISTORY (
    VERSION_ID VARCHAR(100) NOT NULL COMMENT '전체 버전 (표준본: 표준본 버전, 커스텀본: 표준본 버전-커스텀본 버전)',
    STANDARD_VERSION VARCHAR(50) NOT NULL COMMENT '표준 버전 (e.g. 2.5.1)',
    CUSTOM_VERSION VARCHAR(50) NULL COMMENT '고객사 버전 (e.g. companyA.1.0)',
    VERSION_CREATED_AT DATETIME NOT NULL COMMENT '버전 생성 일시',
    VERSION_CREATED_BY VARCHAR(100) NOT NULL COMMENT '버전 생성자',
    SYSTEM_APPLIED_AT DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '시스템 적용 일시',
    SYSTEM_APPLIED_BY VARCHAR(100) NULL COMMENT '시스템 적용 담당자',
    COMMENT TEXT NULL COMMENT '버전 설명',
    PRIMARY KEY (VERSION_ID),
    INDEX idx_version_created_at (VERSION_CREATED_AT),
    INDEX idx_system_applied_at (SYSTEM_APPLIED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='버전 이력 테이블';

-- SMS_INFO 테이블에 SERIAL_NO 컬럼 추가
ALTER TABLE NMS_DB.SMS_INFO
ADD COLUMN `SERIAL_NO` varchar(256) NULL COMMENT '제품 SERIAL NUMBER'
AFTER `PRODUCT_ID`;

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_AGENT_FILE (
    FILE_ID INT NOT NULL AUTO_INCREMENT COMMENT '파일 ID',
    FILE_NAME varchar(200) NOT NULL COMMENT '파일명',
    FILE_DESCRIPTION varchar(1000) NULL COMMENT '파일 설명',
    OS varchar(256) NOT NULL COMMENT '' COMMENT 'O/S (코드분류:2209)',
    AGENT_VERSION varchar(100) NOT NULL COMMENT '에이전트 버전',
    FILE_SIZE bigint NOT NULL COMMENT '파일 크기 (bytes)',
    FILE_PATH varchar(500) NULL COMMENT '서버 내 파일 저장 경로',
    IS_ENABLED char(1) NOT NULL DEFAULT 'Y' COMMENT '활성 여부 [Y:활성, N:비활성]',
    CREATED_AT datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '파일 등록 일시',
    UPDATED_AT datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '파일 수정 일시',
    PRIMARY KEY (FILE_ID),
    UNIQUE KEY UK_OS_FILE_NAME (OS, FILE_NAME),
    UNIQUE KEY UK_OS_AGENT_VERSION (OS, AGENT_VERSION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 에이전트 패치파일 테이블';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_AGENT (
    AGENT_ID INT NOT NULL AUTO_INCREMENT COMMENT '에이전트 ID',
    AGENT_STATUS varchar(30) NOT NULL COMMENT '에이전트 상태 (코드분류:2208)',
    LAST_SEEN_AT datetime NULL COMMENT '마지막 확인 일시',
    CREATED_AT datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '에이전트 생성 일시',
    UPDATED_AT datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '에이전트 갱신 일시',
    MCH_ID INT NULL COMMENT '장비 ID',
    FILE_ID INT NULL COMMENT '파일 ID',
    PRIMARY KEY (AGENT_ID),
    FOREIGN KEY (FILE_ID) REFERENCES SMS_AGENT_FILE(FILE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 에이전트 테이블';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_INDICATOR (
    INDICATOR_ID INT NOT NULL AUTO_INCREMENT COMMENT '지표 ID',
    INDICATOR_TYPE varchar(30) NOT NULL COMMENT '지표 타입 코드 (코드분류:2206)',
    INDICATOR_CD varchar(40) NOT NULL COMMENT '지표 코드',
    INDICATOR_NAME varchar(100) NOT NULL COMMENT '지표 이름',
    INDICATOR_UNIT varchar(30) NOT NULL DEFAULT 'bytes' COMMENT '지표 단위 (코드분류:2207)',
    INDICATOR_DATA_TYPE varchar(30) NOT NULL DEFAULT '2' COMMENT '지표 데이터 타입 코드 (코드분류:2010)',
    EVENT_TYPE char(4) NOT NULL COMMENT '이벤트 타입',
    EVENT_CD char(4) NOT NULL COMMENT '이벤트 코드 (이벤트타입분류:0031~0036)',
    EVENT_LEVEL INT NOT NULL DEFAULT 2 COMMENT '이벤트 레벨 (코드분류:2006)',
    EVENT_MSG_FMT varchar(1024) NOT NULL DEFAULT '$1 $3이벤트:현재[$A$4] 기준[$B$4][$2]' COMMENT '이벤트 메세지 포멧',
    PRIMARY KEY (INDICATOR_ID),
    UNIQUE KEY UK_INDICATOR_CD (INDICATOR_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 지표 테이블';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_AGENT_POLICY_TMPL (
    AGENT_POLICY_TMPL_ID INT NOT NULL AUTO_INCREMENT COMMENT 'SMS 정책 템플릿 ID',
    TMPL_NAME varchar(100) NOT NULL COMMENT '템플릿 이름',
    TMPL_DESCRIPTION varchar(1000) NULL COMMENT '템플릿 설명',
    IS_ENABLED char(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부 [Y:사용, N:미사용]',
    IS_DEFAULT char(1) NOT NULL DEFAULT 'N' COMMENT '기본 제공 템플릿 여부 [Y: 기본템플릿, N: 기본템플릿아님]',
    CREATED_BY varchar(256) NOT NULL COMMENT '생성자',
    CREATED_AT datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    UPDATED_BY varchar(256) NOT NULL COMMENT '수정자',
    UPDATED_AT datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (AGENT_POLICY_TMPL_ID),
    UNIQUE KEY UK_TMPL_NAME (TMPL_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 에이전트 정책 템플릿 테이블';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_AGENT_POLICY_TMPL_INDICATOR (
    AGENT_POLICY_TMPL_ID INT NOT NULL COMMENT 'SMS 정책 템플릿 ID',
    INDICATOR_TYPE varchar(30) NOT NULL COMMENT '지표 타입 코드 (코드분류:2206)',
    IS_COLLECT char(1) NOT NULL DEFAULT 'Y' COMMENT '수집 여부 [Y:수집, N:미수집]',
    COLLECT_INTERVAL INT NOT NULL DEFAULT 300 COMMENT '수집 주기(초)',
    CREATED_BY varchar(256) NOT NULL COMMENT '생성자',
    CREATED_AT datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    UPDATED_BY varchar(256) NOT NULL COMMENT '수정자',
    UPDATED_AT datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (AGENT_POLICY_TMPL_ID, INDICATOR_TYPE),
    FOREIGN KEY (AGENT_POLICY_TMPL_ID) REFERENCES SMS_AGENT_POLICY_TMPL(AGENT_POLICY_TMPL_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 에이전트 정책 템플릿의 지표별 테이블';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_AGENT_POLICY_MAPPING (
    AGENT_ID INT NOT NULL COMMENT '에이전트 ID',
    AGENT_POLICY_TMPL_ID INT NOT NULL COMMENT '에이전트 메트릭별 정책 템플릿 ID',
    CREATED_BY varchar(256) NOT NULL COMMENT '생성자',
    CREATED_AT datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '에이전트 - 에이전트 정책 템플릿 매핑 생성 일시',
    UPDATED_BY varchar(256) NOT NULL COMMENT '수정자',
    UPDATED_AT datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '에이전트 - 에이전트 정책 템플릿 매핑 수정 일시',
    PRIMARY KEY (AGENT_ID, AGENT_POLICY_TMPL_ID),
    FOREIGN KEY (AGENT_ID) REFERENCES SMS_AGENT(AGENT_ID) ON DELETE CASCADE,
    FOREIGN KEY (AGENT_POLICY_TMPL_ID) REFERENCES SMS_AGENT_POLICY_TMPL(AGENT_POLICY_TMPL_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 에이전트 - 에이전트 정책 템플릿 매핑 테이블';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_AGENT_HISTORY (
    AGENT_HISTORY_ID INT NOT NULL AUTO_INCREMENT COMMENT '에이전트 변경 이력 ID',
    HISTORY_TYPE VARCHAR(100) NULL COMMENT '에이전트 변경 이력 타입 (코드분류:2213)',
    AGENT_ID INT NULL COMMENT '에이전트 ID',
    MCH_ID INT NULL COMMENT '장비 ID',
    MCH_NAME VARCHAR(100) NULL COMMENT '장비 이름',
    MCH_IP VARCHAR(100) NULL COMMENT '장비 IP',
    FILE_ID INT NULL COMMENT '파일 ID',
    FILE_NAME VARCHAR(200) NULL COMMENT '파일명',
    AGENT_VERSION VARCHAR(100) NULL COMMENT '에이전트 버전',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '생성 일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자',
    PRIMARY KEY (AGENT_HISTORY_ID),
    INDEX idx_agent_history_agent_id (AGENT_ID),
    INDEX idx_agent_history_mch_id (MCH_ID),
    INDEX idx_agent_history_created_at (CREATED_AT),
    INDEX idx_agent_history_type (HISTORY_TYPE),
    INDEX idx_agent_history_created_by (CREATED_BY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 에이전트 변경 이력 테이블';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_AGENT_JOB_HISTORY (
    AGENT_JOB_HISTORY_ID INT NOT NULL AUTO_INCREMENT COMMENT '에이전트 JOB 수행 이력 ID',
    HISTORY_TYPE VARCHAR(100) NULL COMMENT '에이전트 JOB 수행 이력 타입 (코드분류:2214)',
    AGENT_ID INT NULL COMMENT '에이전트 ID',
    MCH_ID INT NULL COMMENT '장비 ID',
    MCH_NAME VARCHAR(100) NULL COMMENT '장비 이름',
    MCH_IP VARCHAR(100) NULL COMMENT '장비 IP',
    RESPONSE_RESULT VARCHAR(50) NULL COMMENT 'JOB 수행 결과 여부 (코드분류:2215)',
    RESPONSE_STATUS VARCHAR(50) NULL COMMENT '수행 결과 상태',
    RESPONSE_MESSAGE VARCHAR(1000) NULL COMMENT '수행 결과 메시지',
    CREATED_AT DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '생성 일시',
    CREATED_BY VARCHAR(50)  NOT NULL COMMENT '생성자',
    PRIMARY KEY (AGENT_JOB_HISTORY_ID),
    INDEX idx_agent_job_history_agent_id (AGENT_ID),
    INDEX idx_agent_job_history_mch_id (MCH_ID),
    INDEX idx_agent_job_history_created_at (CREATED_AT),
    INDEX idx_agent_job_history_type (HISTORY_TYPE),
    INDEX idx_agent_job_history_status (RESPONSE_STATUS),
    INDEX idx_agent_job_history_created_by (CREATED_BY),
    INDEX idx_agent_job_history_success (RESPONSE_RESULT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 에이전트 JOB 수행 이력 테이블';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_EVENT_POLICY_TMPL (
    EVENT_POLICY_TMPL_ID INT NOT NULL AUTO_INCREMENT COMMENT '이벤트 정책 템플릿 ID',
    TMPL_NAME varchar(100) NOT NULL COMMENT '템플릿 이름',
    TMPL_DESCRIPTION varchar(1000) NULL COMMENT '템플릿 설명',
    IS_ENABLED char(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부 [Y:사용, N:미사용]',
    IS_DEFAULT char(1) NOT NULL DEFAULT 'N' COMMENT '기본 제공 템플릿 여부 [Y: 기본템플릿, N: 기본템플릿아님]',
    CREATED_BY varchar(256) NOT NULL COMMENT '생성자',
    CREATED_AT datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    UPDATED_BY varchar(256) NOT NULL COMMENT '수정자',
    UPDATED_AT datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',

    PRIMARY KEY (EVENT_POLICY_TMPL_ID),
    UNIQUE KEY UK_EVENT_TMPL_NAME (TMPL_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 이벤트 정책 템플릿 테이블';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_EVENT_POLICY_MAPPING (
    AGENT_ID INT NOT NULL COMMENT '에이전트 ID',
    EVENT_POLICY_TMPL_ID INT NOT NULL COMMENT '이벤트 정책 템플릿 ID',
    CREATED_BY varchar(256) NOT NULL COMMENT '생성자',
    CREATED_AT datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    PRIMARY KEY (AGENT_ID, EVENT_POLICY_TMPL_ID),
    FOREIGN KEY FK_SEPM_AGENT_ID (AGENT_ID) REFERENCES SMS_AGENT(AGENT_ID) ON DELETE CASCADE,
    FOREIGN KEY FK_SEPM_TMPL_ID (EVENT_POLICY_TMPL_ID) REFERENCES SMS_EVENT_POLICY_TMPL(EVENT_POLICY_TMPL_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='에이전트 - 이벤트 정책 템플릿 매핑 테이블';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_EVENT_POLICY_THRESHOLD (
    THRESHOLD_ID INT NOT NULL AUTO_INCREMENT COMMENT '임계치 ID',
    THRESHOLD_DESCRIPTION varchar(500) NULL COMMENT '임계치 설명',
    IS_ENABLED char(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부 [Y:사용, N:미사용]',
    INDICATOR_ID INT NOT NULL COMMENT '지표 ID',
    PRIMARY KEY (THRESHOLD_ID),
    FOREIGN KEY FK_SEPT_INDICATOR_ID (INDICATOR_ID) REFERENCES SMS_INDICATOR(INDICATOR_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 이벤트 정책 임계치 테이블';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_EVENT_POLICY_THRESHOLD_CONDITION (
    THRESHOLD_ID INT NOT NULL COMMENT '임계치 ID',
    CONDITION_EVENT_LEVEL INT NOT NULL COMMENT '임계치 조건 이벤트 레벨 (코드분류:2006)',
    CONDITION_VALUE decimal(20,2) NOT NULL COMMENT '임계치 조건 값',
    CONDITION_OPERATOR varchar(20) NOT NULL DEFAULT 'O' COMMENT '임계치 조건 연산자 (코드번호: 2008)',
    PRIMARY KEY (THRESHOLD_ID, CONDITION_EVENT_LEVEL),
    INDEX IDX_CONDITION_EVENT_LEVEL (CONDITION_EVENT_LEVEL),
    FOREIGN KEY FK_SEPTC_THRESHOLD_ID (THRESHOLD_ID) REFERENCES SMS_EVENT_POLICY_THRESHOLD(THRESHOLD_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 이벤트 정책 임계치 조건 테이블';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_EVENT_POLICY_TMPL_MAPPING (
    EVENT_POLICY_TMPL_ID INT NOT NULL COMMENT '이벤트 정책 템플릿 ID',
    THRESHOLD_ID INT NOT NULL COMMENT '임계치 ID',
    PRIMARY KEY (EVENT_POLICY_TMPL_ID, THRESHOLD_ID),
    FOREIGN KEY FK_SEPTM_TMPL_ID (EVENT_POLICY_TMPL_ID) REFERENCES SMS_EVENT_POLICY_TMPL(EVENT_POLICY_TMPL_ID) ON DELETE CASCADE,
    FOREIGN KEY FK_SEPTM_THRESHOLD_ID (THRESHOLD_ID) REFERENCES SMS_EVENT_POLICY_THRESHOLD(THRESHOLD_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 이벤트 템플릿 - 임계치 매핑 테이블';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_PROCESS (
    PROCESS_ID INT NOT NULL AUTO_INCREMENT COMMENT '프로세스 ID',
    PROCESS_NAME VARCHAR(200) NOT NULL COMMENT '프로세스 이름',
    PROCESS_DESCRIPTION VARCHAR(500) NULL COMMENT '프로세스 설명' ,
    OS_TYPE VARCHAR(100) NOT NULL COMMENT '프로세스 O/S타입 (코드분류:2209) (Windows, Linux, macOs)',
    COMMAND_PATTERN_TYPE VARCHAR(50) NOT NULL DEFAULT 'exact' COMMENT '프로세스 명령어 패턴 타입 (코드분류: 2212)',
    COMMAND_PATTERN VARCHAR(1000) NOT NULL COMMENT '프로세스 명령어 패턴 (수집된 프로세스 정보와 매칭할 식별자 역할)',
    IS_ENABLED CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부 (Y/N)',
    IS_DEFAULT CHAR(1) NOT NULL DEFAULT 'N' COMMENT '기본값 여부 (Y/N)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    CREATED_BY VARCHAR(256) NOT NULL COMMENT '생성자',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    UPDATED_BY VARCHAR(256) NOT NULL COMMENT '수정자',
    PRIMARY KEY (PROCESS_ID),
    INDEX idx_os_type (OS_TYPE),
    INDEX idx_process_name (PROCESS_NAME),
    UNIQUE KEY uk_os_type_process_name (OS_TYPE, PROCESS_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 프로세스 테이블';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_PROCESS_MAPPING (
    PROCESS_ID INT NOT NULL COMMENT '프로세스 ID',
    AGENT_ID INT NOT NULL COMMENT '에이전트 ID',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    CREATED_BY VARCHAR(256) NOT NULL COMMENT '생성자',
    PRIMARY KEY (PROCESS_ID, AGENT_ID),
    FOREIGN KEY (PROCESS_ID) REFERENCES SMS_PROCESS(PROCESS_ID) ON DELETE CASCADE,
    FOREIGN KEY (AGENT_ID) REFERENCES SMS_AGENT(AGENT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 에이전트-프로세스 매핑 테이블';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_PROCESS_COMMAND (
    COMMAND_ID INT NOT NULL AUTO_INCREMENT COMMENT '프로세스 커맨드 ID',
    COMMAND_TYPE VARCHAR(50) NOT NULL COMMENT '프로세스 명령어 타입 (코드분류:2210) (start/stop/restart/status/unclassified)',
    COMMAND_NAME VARCHAR(100) NOT NULL COMMENT '프로세스 커맨드 이름',
    COMMAND_DESCRIPTION VARCHAR(500) NULL COMMENT '프로세스 커맨드 설명',
    COMMAND_EXEC VARCHAR(1000) NOT NULL COMMENT '프로세스 실행 커맨드 (전체 커맨드)',
    COMMAND_ORDER INT NOT NULL COMMENT '프로세스 커맨드 순서 (UI표현순서)',
    TIMEOUT_SECONDS INT NULL DEFAULT 30 COMMENT '타임아웃 시간(초)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    CREATED_BY VARCHAR(256) NULL COMMENT '생성자',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    UPDATED_BY VARCHAR(256) NULL COMMENT '수정자',
    PROCESS_ID INT NOT NULL COMMENT '프로세스 ID',
    PRIMARY KEY (COMMAND_ID),
    FOREIGN KEY (PROCESS_ID) REFERENCES SMS_PROCESS(PROCESS_ID) ON DELETE CASCADE,
    INDEX idx_command_type (COMMAND_TYPE),
    UNIQUE KEY uk_process_command_type (PROCESS_ID, COMMAND_TYPE, COMMAND_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 프로세스 명령어 테이블';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_PROCESS_THRESHOLD (
    THRESHOLD_ID INT NOT NULL AUTO_INCREMENT COMMENT '프로세스 임계치 ID',
    PROCESS_ID INT NOT NULL COMMENT '프로세스 ID',
    AGENT_ID INT NOT NULL COMMENT '에이전트 ID',
    CPU_USAGE_PERCENT DECIMAL(20,2) NULL COMMENT '특정 에이전트에 매칭된 프로세스의 CPU 사용률 임계치 설정값',
    MEM_USAGE_PERCENT DECIMAL(20,2) NULL COMMENT '특정 에이전트에 매칭된 프로세스의 MEMORY 사용률 임계치 설정값',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자',
    PRIMARY KEY (THRESHOLD_ID),
    UNIQUE KEY uq_process_id_agent_id (PROCESS_ID, AGENT_ID),
    FOREIGN KEY (PROCESS_ID) REFERENCES SMS_PROCESS(PROCESS_ID) ON DELETE CASCADE,
    FOREIGN KEY (AGENT_ID) REFERENCES SMS_AGENT(AGENT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 프로세스 임계치 테이블';


CREATE TABLE IF NOT EXISTS NMS_DB.SMS_PROCESS_COMMAND_HISTORY (
    COMMAND_HISTORY_ID INT NOT NULL AUTO_INCREMENT COMMENT '프로세스 커맨드 실행이력 ID',
    PROCESS_ID INT NULL COMMENT '프로세스 ID',
    PROCESS_NAME VARCHAR(200) NULL COMMENT '프로세스 이름',
    AGENT_ID INT NULL COMMENT '에이전트 ID',
    MCH_ID INT NULL COMMENT '장비 ID',
    MCH_NAME VARCHAR(100) NULL COMMENT '장비 이름',
    MCH_IP VARCHAR(100) NULL COMMENT '장비 IP',
    COMMAND_ID INT NULL COMMENT '프로세스 커맨드 ID',
    COMMAND_TYPE VARCHAR(50) NULL COMMENT '프로세스 명령어 타입 (코드분류:2210) (start/stop/restart/status/unclassified)',
    COMMAND_NAME VARCHAR(100) NULL COMMENT '프로세스 커맨드 이름',
    COMMAND_EXEC VARCHAR(1000) NULL COMMENT '프로세스 실행 커맨드 (전체 커맨드)',
    COMMAND_EXEC_TIME INT NULL DEFAULT 60 COMMENT '프로세스 커맨드 실행 시간(초)',
    EXECUTION_STATUS VARCHAR(20) NULL DEFAULT 'PENDING' COMMENT '실행 상태 (PENDING/SUCCESS/FAILED/TIMEOUT)',
    EXECUTION_RESULT TEXT NULL COMMENT '실행 결과',
    ERROR_MESSAGE TEXT NULL COMMENT '오류 메시지',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자',
    PRIMARY KEY (COMMAND_HISTORY_ID),
    INDEX idx_created_at (CREATED_AT),
    INDEX idx_execution_status (EXECUTION_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 프로세스 명령어 수행 이력 테이블';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_EX_TIME_TMPL (
    EX_TMPL_ID INT NOT NULL AUTO_INCREMENT COMMENT '템플릿 ID',
    EX_TMPL_NM VARCHAR(256) NOT NULL COMMENT '템플릿 이름',
    EX_TMPL_DESC VARCHAR(600) NULL COMMENT '템플릿 설명',
    USE_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '사용 여부(Y/N)',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP NULL COMMENT '등록시간',
    REG_ID VARCHAR(256) NULL COMMENT '등록자',
    UPD_DT DATETIME DEFAULT CURRENT_TIMESTAMP NULL COMMENT '변경시간',
    UPD_ID VARCHAR(256) NULL COMMENT '변경자',
    PRIMARY KEY (EX_TMPL_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 이벤트 예외시간 템플릿';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_EX_TIME_SCHEDULE (
    SCHEDULE_ID BIGINT AUTO_INCREMENT COMMENT 'SCHEDULE ID',
    EX_TMPL_ID INT NULL COMMENT '템플릿 ID',
    RUN_MODE CHAR(1) NOT NULL COMMENT '실행 구분(1:한번, 2:반복)(코드분류:2015)',
    RUN_TYPE CHAR(1) NOT NULL COMMENT '실행 종류(0:1회성, 1:매일, 2:매주, 3:매월)(코드분류:2016)',
    APPLY_STAT_DATE DATETIME NOT NULL COMMENT '정책적용 시작일시',
    APPLY_END_DATE DATETIME NOT NULL COMMENT '정책적용 종료일시',
    REPEAT_START_TIME TIME NOT NULL COMMENT '반복 시작시간',
    REPEAT_END_TIME TIME NOT NULL COMMENT '반복 종료시간',
    USE_YN CHAR(1) DEFAULT 'Y' NULL COMMENT '사용 여부(Y/N)',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP NULL COMMENT '등록시간',
    REG_ID VARCHAR(256) NULL COMMENT '등록자',
    UPD_DT DATETIME DEFAULT CURRENT_TIMESTAMP NULL COMMENT '변경시간',
    UPD_ID VARCHAR(256) NULL COMMENT '변경자',
    PRIMARY KEY (SCHEDULE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 이벤트 예외시간 스케줄';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_EX_TIME_SCHEDULE_WEEKLY (
    WEEKLY_ID BIGINT AUTO_INCREMENT COMMENT '주간 ID',
    SCHEDULE_ID BIGINT NOT NULL COMMENT 'SCHEDULE ID',
    MON_YN CHAR(1) DEFAULT 'N' NULL COMMENT '월요일 여부',
    TUE_YN CHAR(1) DEFAULT 'N' NULL COMMENT '화요일 여부',
    WED_YN CHAR(1) DEFAULT 'N' NULL COMMENT '수요일 여부',
    THU_YN CHAR(1) DEFAULT 'N' NULL COMMENT '목요일 여부',
    FRI_YN CHAR(1) DEFAULT 'N' NULL COMMENT '금요일 여부',
    SAT_YN CHAR(1) DEFAULT 'N' NULL COMMENT '토요일 여부',
    SUN_YN CHAR(1) DEFAULT 'N' NULL COMMENT '일요일 여부',
    PRIMARY KEY (WEEKLY_ID),
    FOREIGN KEY (SCHEDULE_ID) REFERENCES SMS_EX_TIME_SCHEDULE(SCHEDULE_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 이벤트 예외시간 주간 스케줄';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_EX_TIME_SCHEDULE_MONTHLY (
    MONTHLY_ID BIGINT AUTO_INCREMENT COMMENT '월간 ID',
    SCHEDULE_ID BIGINT NOT NULL COMMENT 'SCHEDULE ID',
    DAY_OF_MONTH INT NOT NULL COMMENT '월의 일자 (1-31)',
    PRIMARY KEY (MONTHLY_ID),
    FOREIGN KEY (SCHEDULE_ID) REFERENCES SMS_EX_TIME_SCHEDULE(SCHEDULE_ID) ON DELETE CASCADE,
    CHECK (DAY_OF_MONTH BETWEEN 1 AND 31)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 이벤트 예외시간 월간 스케줄';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_EX_TIME_SCHEDULE_HOLIDAY (
    HOLIDAY_ID BIGINT AUTO_INCREMENT COMMENT '휴일 ID',
    SCHEDULE_ID BIGINT NOT NULL COMMENT 'SCHEDULE ID',
    HOLIDAY_DATE DATE NOT NULL COMMENT '휴일 날짜',
    DESCRIPTION VARCHAR(200) NULL COMMENT '휴일 설명',
    PRIMARY KEY (HOLIDAY_ID),
    FOREIGN KEY (SCHEDULE_ID) REFERENCES SMS_EX_TIME_SCHEDULE(SCHEDULE_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 이벤트 예외시간 휴일 스케줄';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_EX_TIME_INDICATOR_MAPPING (
    MAPPING_ID INT AUTO_INCREMENT COMMENT '매핑 ID',
    EX_TMPL_ID INT NOT NULL COMMENT '템플릿 ID',
    INDICATOR_ID INT NOT NULL COMMENT '지표 ID',
    CREATE_USER VARCHAR(50) NULL COMMENT '생성자',
    CREATE_DTM DATETIME DEFAULT CURRENT_TIMESTAMP NULL COMMENT '생성일시',
    UPDATE_USER VARCHAR(50) NULL COMMENT '수정자',
    UPDATE_DTM DATETIME DEFAULT CURRENT_TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (MAPPING_ID),
    FOREIGN KEY (EX_TMPL_ID) REFERENCES SMS_EX_TIME_TMPL(EX_TMPL_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 이벤트 예외시간 지표 매핑';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_EX_TIME_AGENT_MAPPING (
    MAPPING_ID INT AUTO_INCREMENT COMMENT '매핑 ID',
    EX_TMPL_ID INT NOT NULL COMMENT '템플릿 ID',
    AGENT_ID INT NOT NULL COMMENT '에이전트 ID',
    CREATE_USER VARCHAR(50) NULL COMMENT '생성자',
    CREATE_DTM DATETIME DEFAULT CURRENT_TIMESTAMP NULL COMMENT '생성일시',
    UPDATE_USER VARCHAR(50) NULL COMMENT '수정자',
    UPDATE_DTM DATETIME DEFAULT CURRENT_TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (MAPPING_ID),
    FOREIGN KEY (EX_TMPL_ID) REFERENCES SMS_EX_TIME_TMPL(EX_TMPL_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 이벤트 예외시간 에이전트 매핑';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_FILE_MONITOR_POLICY (
    POLICY_ID BIGINT AUTO_INCREMENT COMMENT '정책 ID',
    AGENT_ID INT NOT NULL COMMENT '에이전트 ID',
    POLICY_NAME VARCHAR(200) NOT NULL COMMENT '정책명',
    TARGET_PATH VARCHAR(500) NOT NULL COMMENT '대상 경로',
    IS_USED TINYINT(1) DEFAULT 0 NULL COMMENT '사용 여부',
    IS_EXIST_EVENT TINYINT(1) DEFAULT 0 NULL COMMENT '존재 이벤트 여부',
    COLLECT_INTERVAL INT DEFAULT 60 NOT NULL COMMENT '수집 주기(초)',
    DESCRIPTION VARCHAR(500) NULL COMMENT '설명',
    CREATED_BY VARCHAR(256) NOT NULL COMMENT '생성자',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '생성 일시',
    UPDATED_BY VARCHAR(256) NOT NULL COMMENT '수정자',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (POLICY_ID),
    INDEX idx_agent (AGENT_ID),
    INDEX idx_target_path (TARGET_PATH(255))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='디렉토리 모니터링 정책 테이블';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_FILE_MONITOR_POLICY_DETAIL (
    POLICY_ID BIGINT AUTO_INCREMENT COMMENT '정책 ID',
    PARENT_POLICY_ID BIGINT NOT NULL COMMENT '디렉토리 정책 ID',
    AGENT_ID INT NOT NULL COMMENT '에이전트 ID',
    POLICY_NAME VARCHAR(200) NOT NULL COMMENT '정책명',
    TARGET_PATH VARCHAR(500) NOT NULL COMMENT '파일 경로',
    FILE_NAME_PATTERN VARCHAR(255) NULL COMMENT '파일명 패턴',
    IS_EXIST_EVENT TINYINT(1) DEFAULT 0 NULL COMMENT '존재 이벤트 여부',
    IS_USED TINYINT(1) DEFAULT 0 NULL COMMENT '사용 여부',
    COLLECT_INTERVAL INT DEFAULT 60 NOT NULL COMMENT '수집 주기(초)',
    DESCRIPTION VARCHAR(500) NULL COMMENT '설명',
    CREATED_BY VARCHAR(256) NOT NULL COMMENT '생성자',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '생성 일시',
    UPDATED_BY VARCHAR(256) NOT NULL COMMENT '수정자',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (POLICY_ID),
    FOREIGN KEY (PARENT_POLICY_ID) REFERENCES SMS_FILE_MONITOR_POLICY(POLICY_ID) ON DELETE CASCADE,
    INDEX idx_agent (AGENT_ID),
    INDEX idx_parent_policy (PARENT_POLICY_ID),
    INDEX idx_target_path (TARGET_PATH(255))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='파일 모니터링 상세 정책 테이블';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_LOG_MONITOR_POLICY (
    POLICY_ID INT AUTO_INCREMENT COMMENT '정책 ID',
    AGENT_ID INT NOT NULL COMMENT '에이전트 ID',
    POLICY_NAME VARCHAR(100) NOT NULL COMMENT '정책명',
    DESCRIPTION VARCHAR(500) NULL COMMENT '정책 설명',
    IS_USED TINYINT(1) DEFAULT 0 NULL COMMENT '사용 상태',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자',
    CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP NULL COMMENT '생성일시',
    UPDATED_BY VARCHAR(50) NULL COMMENT '수정자',
    UPDATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (POLICY_ID),
    FOREIGN KEY (AGENT_ID) REFERENCES SMS_AGENT(AGENT_ID) ON DELETE CASCADE,
    INDEX idx_agent_id (AGENT_ID),
    INDEX idx_is_used (IS_USED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='로그 모니터링 정책 마스터';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_LOG_MONITOR_POLICY_DETAIL (
    DETAIL_ID INT AUTO_INCREMENT COMMENT '상세 ID',
    POLICY_ID INT NOT NULL COMMENT '정책 ID',
    FILE_NAME VARCHAR(200) NULL COMMENT '로그 파일명',
    FILE_PATH VARCHAR(500) NULL COMMENT '로그 파일 경로',
    FILE_TYPE VARCHAR(20) NULL COMMENT '파일 타입 (TEXT/JSON/XML/CSV)',
    FILE_ENCODING VARCHAR(20) DEFAULT 'UTF-8' NULL COMMENT '파일 인코딩',
    LOG_LEVEL VARCHAR(20) NULL COMMENT '수집 로그 레벨 (DEBUG/INFO/WARN/ERROR/ALL)',
    FILE_PATTERN VARCHAR(200) NULL COMMENT '파일명 패턴 (정규식)',
    FILTER_TYPE VARCHAR(20) NULL COMMENT '필터 타입 (INCLUDE/EXCLUDE)',
    FILTER_PATTERN VARCHAR(500) NULL COMMENT '필터 패턴 (정규식)',
    IS_USED TINYINT(1) DEFAULT 0 NULL COMMENT '사용 상태',
    SORT_ORDER INT DEFAULT 1 NULL COMMENT '정렬 순서',
    DESCRIPTION VARCHAR(500) NULL COMMENT '상세 설명',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자',
    CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP NULL COMMENT '생성일시',
    UPDATED_BY VARCHAR(50) NULL COMMENT '수정자',
    UPDATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (DETAIL_ID),
    FOREIGN KEY (POLICY_ID) REFERENCES SMS_LOG_MONITOR_POLICY(POLICY_ID) ON DELETE CASCADE,
    INDEX idx_is_used (IS_USED),
    INDEX idx_policy_id (POLICY_ID),
    INDEX idx_sort_order (SORT_ORDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='로그 모니터링 정책 상세';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_SERVICE_MONITOR_POLICY (
    POLICY_ID BIGINT AUTO_INCREMENT COMMENT '정책 ID',
    AGENT_ID INT NOT NULL COMMENT '에이전트 ID',
    POLICY_NAME VARCHAR(100) NOT NULL COMMENT '정책명',
    IS_USED TINYINT(1) DEFAULT 0 NULL COMMENT '사용 상태',
    DESCRIPTION VARCHAR(500) NULL COMMENT '비고',
    CREATED_BY VARCHAR(256) NOT NULL COMMENT '생성자',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '생성 일시',
    UPDATED_BY VARCHAR(256) NOT NULL COMMENT '수정자',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (POLICY_ID),
    INDEX IDX_AGENT_ID (AGENT_ID),
    INDEX IDX_IS_USED (IS_USED),
    INDEX IDX_POLICY_NAME (POLICY_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 서비스 모니터링 정책';

CREATE TABLE IF NOT EXISTS NMS_DB.SMS_SERVICE_MONITOR_POLICY_DETAIL (
    DETAIL_ID BIGINT AUTO_INCREMENT COMMENT '상세 정책 ID',
    PARENT_POLICY_ID BIGINT NOT NULL COMMENT '상위 정책 ID',
    AGENT_ID INT NOT NULL COMMENT '에이전트 ID',
    POLICY_NAME VARCHAR(100) NOT NULL COMMENT '정책명',
    PORT_NO VARCHAR(20) NOT NULL COMMENT '포트번호',
    PORT_NAME VARCHAR(100) NULL COMMENT '포트명 (예: WEB, API, DB)',
    COLLECT_CYCLE INT DEFAULT 60 NULL COMMENT '수집주기 (초 단위)',
    IS_USED TINYINT(1) DEFAULT 0 NULL COMMENT '사용 상태',
    SORT_ORDER INT DEFAULT 0 NULL COMMENT '정렬순서',
    DESCRIPTION VARCHAR(500) NULL COMMENT '비고',
    CREATED_BY VARCHAR(256) NOT NULL COMMENT '생성자',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '생성 일시',
    UPDATED_BY VARCHAR(256) NOT NULL COMMENT '수정자',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (DETAIL_ID),
    FOREIGN KEY (PARENT_POLICY_ID) REFERENCES SMS_SERVICE_MONITOR_POLICY(POLICY_ID) ON DELETE CASCADE,
    INDEX IDX_AGENT_ID (AGENT_ID),
    INDEX IDX_IS_USED (IS_USED),
    INDEX IDX_PARENT_POLICY_ID (PARENT_POLICY_ID),
    INDEX IDX_PORT_NO (PORT_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='SMS 서비스 모니터링 포트 상세 정책';
SELECT 'DDL 패치 완료' AS RESULT;
