/*
 * 
 * 대상 설치본 버전: InfraEye-2.0.0.241127-STD.tar.gz,  infra2_img_2.0.0_250204.tar.gz
 * 패치본 생성일: 2025-10-27
 * 주요 내용: SMS 추가로 인한 뷰 변경
 * - V_MCH_INFO, V_MCH_INFO_EN, 
 * - V_PRIV_MCH_INFO_EN, V_PRIV_MCH_INFO
 *  
 * */ 
 
USE NMS_DB;

DROP TABLE IF EXISTS V_MCH_INFO;
DROP VIEW IF EXISTS V_MCH_INFO;

CREATE VIEW V_MCH_INFO AS
SELECT M.MCH_ID
	    ,M.MCH_IP
	    ,T.TARGET_NM AS MCH_NM
	    ,MU.UI_SYS_NAME
	    ,MT.MCH_GB_CD
	    ,MG.MCH_GB_NM AS MCH_GB_NM
	    ,MT.MCH_TYPE_CD
	    ,MT.MCH_TYPE_NM
	    ,MM.VENDOR_CD
	    ,MT.DEVICE_TYPE_CD
	    ,CD2.CD_NM AS VENDOR_NM
	    ,M.MODEL_ID
	    ,MM.MODEL_NM
	    ,MA.SNMP_TMPL_ID
	    ,MA.TERMINAL_TMPL_ID
	    ,MC.NMS_SVR_ID
	    ,MC.ICMP_TMPL_ID
	    ,MC.PERF_TMPL_ID
	    ,MC.UDI_TMPL_ID
	    ,MC.CONFIBACK_TMPL_ID
	    ,MC.EX_TIME_TMPL_ID
	    ,MC.NOTI_TMPL_ID
	    ,IFNULL((SELECT TMPL_ID FROM AI_LEARN_MCH_COLLECT_POLICY WHERE MCH_ID = M.MCH_ID), 0) AS AI_TMPL_ID
	    ,(SELECT CASE WHEN COUNT(MCH_ID)>0 THEN 'Y' ELSE 'N' END
	     FROM FLOW_COLLECT_POLICY WHERE MCH_ID = M.MCH_ID) AS FLOW_MNG_YN
    ,M.SYS_OBJECTID
    ,M.SYS_NAME
    ,M.SYS_DESC
    ,M.REG_DT
    ,M.UPD_DT
FROM MCH_INFO M
INNER JOIN TARGET_INFO T ON M.MCH_ID = T.TARGET_ID AND T.TARGET_CD = '01'
INNER JOIN MCH_ACCOUNT MA ON M.MCH_ID = MA.MCH_ID
INNER JOIN MCH_COLLECT_POLICY MC ON M.MCH_ID = MC.MCH_ID
INNER JOIN MCH_UI_INFO MU ON M.MCH_ID = MU.MCH_ID
INNER JOIN MCH_TYPE_INFO MT ON MT.MCH_TYPE_CD = MU.MCH_TYPE_CD
INNER JOIN MCH_GB_INFO MG ON MG.MCH_GB_CD = MT.MCH_GB_CD
INNER JOIN MCH_MODEL_INFO MM ON MM.MODEL_ID = M.MODEL_ID
INNER JOIN CD_INFO CD2 ON CD2.CD_ID = MM.VENDOR_CD AND CD2.CD_GROUP_ID = '2031'
WITH CHECK OPTION;

###################################################################################################

DROP TABLE IF EXISTS V_MCH_INFO_EN;
DROP VIEW IF EXISTS V_MCH_INFO_EN;

CREATE VIEW V_MCH_INFO_EN AS
SELECT M.MCH_ID                   
	    ,M.MCH_IP
	    ,T.TARGET_NM AS MCH_NM
	    ,MU.UI_SYS_NAME
	    ,MG.MCH_GB_NM_EN AS MCH_GB_NM
	    ,MT.MCH_TYPE_CD
	    ,MT.MCH_TYPE_NM_EN AS MCH_TYPE_NM
	    ,MM.VENDOR_CD
	    ,MT.DEVICE_TYPE_CD
	    ,IFNULL(CD2.CD_NM_EN,CD2.CD_NM) AS VENDOR_NM
	    ,M.MODEL_ID
	    ,MM.MODEL_NM
	    ,MA.SNMP_TMPL_ID
	    ,MA.TERMINAL_TMPL_ID
	    ,MC.NMS_SVR_ID
	    ,MC.ICMP_TMPL_ID
	    ,MC.PERF_TMPL_ID
	    ,MC.UDI_TMPL_ID
	    ,MC.CONFIBACK_TMPL_ID
	    ,MC.EX_TIME_TMPL_ID
	    ,MC.NOTI_TMPL_ID
	    ,IFNULL((SELECT TMPL_ID FROM AI_LEARN_MCH_COLLECT_POLICY WHERE MCH_ID = M.MCH_ID), 0) AS AI_TMPL_ID
	    ,(SELECT CASE WHEN COUNT(MCH_ID)>0 THEN 'Y' ELSE 'N' END
FROM FLOW_COLLECT_POLICY WHERE MCH_ID = M.MCH_ID) AS FLOW_MNG_YN
    ,M.SYS_OBJECTID
    ,M.SYS_NAME
    ,M.SYS_DESC
    ,M.REG_DT
    ,M.UPD_DT
FROM MCH_INFO M
INNER JOIN TARGET_INFO T ON M.MCH_ID = T.TARGET_ID AND T.TARGET_CD = '01'
INNER JOIN MCH_ACCOUNT MA ON M.MCH_ID = MA.MCH_ID
INNER JOIN MCH_COLLECT_POLICY MC ON M.MCH_ID = MC.MCH_ID
INNER JOIN MCH_UI_INFO MU ON M.MCH_ID = MU.MCH_ID
INNER JOIN MCH_TYPE_INFO MT ON MT.MCH_TYPE_CD = MU.MCH_TYPE_CD
INNER JOIN MCH_GB_INFO MG ON MG.MCH_GB_CD = MT.MCH_GB_CD
INNER JOIN MCH_MODEL_INFO MM ON MM.MODEL_ID = M.MODEL_ID
INNER JOIN CD_INFO CD2 ON CD2.CD_ID = MM.VENDOR_CD AND CD2.CD_GROUP_ID = '2031'
WITH CHECK OPTION;

###################################################################################################

DROP TABLE IF EXISTS V_PRIV_MCH_INFO_EN;
DROP VIEW IF EXISTS V_PRIV_MCH_INFO_EN;

CREATE VIEW V_PRIV_MCH_INFO_EN AS
SELECT V.MCH_ID,
       V.MCH_IP,
       V.MCH_NM,
       V.SYS_NAME,
       V.MCH_GB_NM,
       V.MCH_TYPE_CD,
       V.MCH_TYPE_NM,
       V.VENDOR_CD,
       V.VENDOR_NM,
       V.MODEL_ID,
       V.MODEL_NM,
       V.SNMP_TMPL_ID,
       V.TERMINAL_TMPL_ID,
       V.NMS_SVR_ID,
       V.ICMP_TMPL_ID,
       V.PERF_TMPL_ID,
       V.UDI_TMPL_ID,
       V.CONFIBACK_TMPL_ID,
       V.EX_TIME_TMPL_ID,
       V.NOTI_TMPL_ID,
       V.AI_TMPL_ID,
       V.FLOW_MNG_YN,
       V.DEVICE_TYPE_CD
FROM NMS_DB.V_MCH_INFO_EN V
JOIN (
    SELECT D.MCH_ID
    FROM NMS_DB.MCH_INFO D
    WHERE (
              (SELECT ROLE_ID
               FROM NMS_DB.USER_INFO
               WHERE USER_ID = FC_NMS_GET_TMP_USER_ID()) = 1
              AND D.MCH_ID > 0
          )
       OR (
              (SELECT ROLE_ID
               FROM NMS_DB.USER_INFO
               WHERE USER_ID = FC_NMS_GET_TMP_USER_ID()) > 1
              AND D.MCH_ID = 0
          )

    UNION
    SELECT C.OBJ_ID AS MCH_ID
    FROM NMS_DB.USER_PRIV_GRANT_LIST A
    JOIN NMS_DB.GROUP_INFO B ON A.DEST_ID = B.GROUP_ID
    JOIN NMS_DB.GROUP_OBJ_LIST C ON B.GROUP_ID = C.GROUP_ID
    WHERE B.GROUP_CD = '1'
      AND A.USER_ID = FC_NMS_GET_TMP_USER_ID()
) T
ON T.MCH_ID = V.MCH_ID
WITH CHECK OPTION;

###################################################################################################

DROP TABLE IF EXISTS V_PRIV_MCH_INFO;
DROP VIEW IF EXISTS V_PRIV_MCH_INFO;

CREATE VIEW V_PRIV_MCH_INFO AS
SELECT V.MCH_ID,
       V.MCH_IP,
       V.MCH_NM,
       V.SYS_NAME,
       V.MCH_GB_CD,
       V.MCH_GB_NM,
       V.MCH_TYPE_CD,
       V.MCH_TYPE_NM,
       V.VENDOR_CD,
       V.VENDOR_NM,
       V.MODEL_ID,
       V.MODEL_NM,
       V.SNMP_TMPL_ID,
       V.TERMINAL_TMPL_ID,
       V.NMS_SVR_ID,
       V.ICMP_TMPL_ID,
       V.PERF_TMPL_ID,
       V.UDI_TMPL_ID,
       V.CONFIBACK_TMPL_ID,
       V.EX_TIME_TMPL_ID,
       V.NOTI_TMPL_ID,
       V.AI_TMPL_ID,
       V.FLOW_MNG_YN,
       V.DEVICE_TYPE_CD
FROM NMS_DB.V_MCH_INFO V
JOIN (
    SELECT D.MCH_ID
    FROM NMS_DB.MCH_INFO D
    WHERE (
      (SELECT ROLE_ID
       FROM NMS_DB.USER_INFO
       WHERE USER_ID = FC_NMS_GET_TMP_USER_ID()) = 1
      AND D.MCH_ID > 0
          )
       OR (
              (SELECT ROLE_ID
               FROM NMS_DB.USER_INFO
               WHERE USER_ID = FC_NMS_GET_TMP_USER_ID()) > 1
              AND D.MCH_ID = 0
          )

    UNION
    SELECT C.OBJ_ID AS MCH_ID
    FROM NMS_DB.USER_PRIV_GRANT_LIST A
    JOIN NMS_DB.GROUP_INFO B
      ON A.DEST_ID = B.GROUP_ID
    JOIN NMS_DB.GROUP_OBJ_LIST C
      ON B.GROUP_ID = C.GROUP_ID
    WHERE B.GROUP_CD = '1'
      AND A.USER_ID = FC_NMS_GET_TMP_USER_ID()
) T
ON T.MCH_ID = V.MCH_ID
WITH CHECK OPTION;
SELECT 'VIEW 패치 완료' AS RESULT;