USE NMS_DB;

-- 디렉토리 모니터링 정책 테이블
CREATE TABLE IF NOT EXISTS NMS_DB.SMS_FILE_MONITOR_POLICY (
    POLICY_ID BIGINT AUTO_INCREMENT COMMENT '정책 ID',
    AGENT_ID INT NOT NULL COMMENT '에이전트 ID',
    POLICY_NAME VARCHAR(200) NOT NULL COMMENT '정책명',
    TARGET_PATH VARCHAR(500) NOT NULL COMMENT '대상 경로',
    IS_USED TINYINT(1) DEFAULT 0 NULL COMMENT '사용 여부',
    IS_EXIST_EVENT TINYINT(1) DEFAULT 0 NULL COMMENT '존재 이벤트 여부',
    COLLECT_INTERVAL INT DEFAULT 60 NOT NULL COMMENT '수집 주기(초)',
    DESCRIPTION VARCHAR(500) NULL COMMENT '설명',
    CREATED_BY VARCHAR(256) NOT NULL COMMENT '생성자',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '생성 일시',
    UPDATED_BY VARCHAR(256) NOT NULL COMMENT '수정자',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (POLICY_ID),
    INDEX idx_agent (AGENT_ID),
    INDEX idx_target_path (TARGET_PATH(255))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='디렉토리 모니터링 정책 테이블';


-- 파일 모니터링 상세 정책 테이블
CREATE TABLE IF NOT EXISTS NMS_DB.SMS_FILE_MONITOR_POLICY_DETAIL (
    DETAIL_ID BIGINT AUTO_INCREMENT COMMENT '정책별 파일 ID',
    PARENT_POLICY_ID BIGINT NOT NULL COMMENT '디렉토리 정책 ID',
    AGENT_ID INT NOT NULL COMMENT '에이전트 ID',
    POLICY_NAME VARCHAR(200) NOT NULL COMMENT '정책명',
    FILE_NAME VARCHAR(100) NOT NULL COMMENT '파일명',
    FILE_NAME_PATTERN VARCHAR(255) NULL COMMENT '파일명 패턴',
    IS_USED TINYINT(1) DEFAULT 0 NULL COMMENT '사용 여부',
    IS_EXIST_EVENT TINYINT(1) DEFAULT 0 NULL COMMENT '존재 이벤트 여부',    
    COLLECT_INTERVAL INT DEFAULT 60 NOT NULL COMMENT '수집 주기(초)',
    DESCRIPTION VARCHAR(500) NULL COMMENT '설명',
    CREATED_BY VARCHAR(256) NOT NULL COMMENT '생성자',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '생성 일시',
    UPDATED_BY VARCHAR(256) NOT NULL COMMENT '수정자',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (DETAIL_ID),
    INDEX idx_agent (AGENT_ID),
    INDEX idx_parent_policy (PARENT_POLICY_ID),
    INDEX idx_file_name (FILE_NAME),
    FOREIGN KEY (PARENT_POLICY_ID) REFERENCES SMS_FILE_MONITOR_POLICY(POLICY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='파일 모니터링 상세 정책 테이블';


-- 파일 모니터링 수집 메트릭 테이블
CREATE TABLE IF NOT EXISTS NMS_DB.SMS_FILE_MONITOR_METRIC (
    METRIC_ID BIGINT AUTO_INCREMENT COMMENT '수집 ID',
    POLICY_ID BIGINT NOT NULL COMMENT '정책 ID',
    DETAIL_ID INT NULL COMMENT '파일 ID',
    OBJECT_NAME VARCHAR(100) NULL COMMENT '디렉토리/파일명',
    OBJECT_STATUS VARCHAR(50) NOT NULL COMMENT '상태',
    OBJECT_SIZE VARCHAR(100) NOT NULL COMMENT '사이즈',
    OBJECT_PERMISSIONS VARCHAR(50) NOT NULL COMMENT '권한',
    OBJECT_OWNER VARCHAR(50) NOT NULL COMMENT '소유자',
    NUM_OF_OBJECTS INT NOT NULL COMMENT '파일개수',
    CREATED_BY VARCHAR(256) NOT NULL COMMENT '생성자',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '생성 일시',
    UPDATED_BY VARCHAR(256) NOT NULL COMMENT '수정자',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (METRIC_ID),    
    FOREIGN KEY (POLICY_ID) REFERENCES SMS_FILE_MONITOR_POLICY(POLICY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='파일 모니터링 수집 메트릭 테이블';


-- 파일 모니터링 변경 이력 테이블
CREATE TABLE IF NOT EXISTS NMS_DB.SMS_FILE_MONITOR_METRIC_CHG_HISTORY (
    CHG_ID BIGINT AUTO_INCREMENT COMMENT '변경 이력 ID',
    POLICY_ID BIGINT NOT NULL COMMENT '정책 ID',
    OBJECT_STATUS VARCHAR(50) NOT NULL COMMENT '상태',
    OBJECT_SIZE VARCHAR(100) NOT NULL COMMENT '사이즈',
    OBJECT_PERMISSIONS VARCHAR(50) NOT NULL COMMENT '권한',
    OBJECT_OWNER VARCHAR(50) NOT NULL COMMENT '소유자',
    NUM_OF_OBJECTS INT NOT NULL COMMENT '파일개수',
    ORDER_NUM INT NULL COMMENT '이력 정렬',
    CREATED_BY VARCHAR(256) NOT NULL COMMENT '생성자',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '생성 일시',
    PRIMARY KEY (CHG_ID),
    FOREIGN KEY (POLICY_ID) REFERENCES SMS_FILE_MONITOR_POLICY(POLICY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='파일 모니터링 변경 이력 테이블';

SELECT 'DDL 패치 완료' AS RESULT;