USE NMS_DB;

-- 퍼센트 지표 기본 색상 변경 (기존: 0, 21, 41, 61 모두 #39C3E6)
UPDATE NMS_DB.ITEM_COLOR_SETUP
SET COLOR_TABLE = CASE
    WHEN ITEM_GB=2 AND ITEM_CD = 0 THEN '#FFFFFF'
    WHEN ITEM_GB=2 AND ITEM_CD = 21 THEN '#39C3E6'
    WHEN ITEM_GB=2 AND ITEM_CD = 41 THEN '#CDE639'
    WHEN ITEM_GB=2 AND ITEM_CD = 61 THEN '#E69439'
    WHEN ITEM_GB=2 AND ITEM_CD = 81 THEN '#F04F4F'
    ELSE COLOR_TABLE
END
WHERE (ITEM_GB=2 AND ITEM_CD = 0)
   OR (ITEM_GB=2 AND ITEM_CD = 21)   
   OR (ITEM_GB=2 AND ITEM_CD = 41)
   OR (ITEM_GB=2 AND ITEM_CD = 61)
   OR (ITEM_GB=2 AND ITEM_CD = 81);

SELECT 'DML 패치 완료' AS RESULT;